apiVersion: v1
kind: Service
metadata:
  name: scraper-service
spec:
  type: NodePort
  selector:
    app: scraper-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  
    - name: metrics
      protocol: TCP
      port: 9095
      targetPort: 9095
      nodePort: 30095  
