apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-service
  template:
    metadata:
      labels:
        app: scraper-service
    spec:
      containers:
      - name: scraper-service
        image: momaaz0/scraper_service.py:latest
        ports:
        - containerPort: 8080
       
