name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Build Docker image
      run: docker build . -t scraper_service:latest

    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push scraper_service:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v5
      with:
        namespace: default
        manifests: |
          deployment.yaml
        images: |
          scraper_service:latest
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
