name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t momaaz0/scraper_service.py:latest .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 -p 9095:9095 --name scraper_service momaaz0/scraper_service.py:latest

    - name: Wait for the service to be available
      run: |
        for i in {1..10}; do
          if docker exec scraper_service curl -s http://localhost:8080; then
            break
          fi
          echo "Waiting for the service to be available..."
          sleep 3
        done

    - name: Run tests
      run: python -m unittest discover

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push momaaz0/scraper_service.py:latest

    - name: Stop and remove Docker container
      run: |
        docker stop scraper_service
        docker rm scraper_service

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: v1.21.0

    - name: Configure kubectl
      run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
